services:
  funpayvertex:
    build: .
    container_name: funpayvertex
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - ./configs:/app/configs
      - ./logs:/app/logs
      - ./storage:/app/storage
      - ./plugins:/app/plugins
